First assembler instructions
azul-research/jdk-riscv pull request #30
Opened 2019-11-12 16:46 UTC by AntonKozlov

A lot of work done for encodings, great!

Can we merge this?

2019-11-13 10:13 UTC, Geckostya requested changes
Add more RISCV specification links, it is hard to find code to docs accordance

2019-11-13 10:13 UTC, Geckostya commented on src/hotspot/cpu/riscv/assembler_riscv.hpp
> +        ((x & 0x1e) << 7) | ((x & 0x7e0) >> 5 << 25) |
I think that `((x >> 5) & 0x3f) << 25` is more readable when `((x & 0x7e0) >> 5 << 25)`

2019-11-13 10:13 UTC, Geckostya commented on src/hotspot/cpu/riscv/assembler_riscv.hpp
> +        ((unsigned)(x >> 12) << 31) | (((x >> 11) & 0x1) << 6)
`(((x >> 11) & 0x1) << 6)` it should be in 7th bit, not 6th

2019-11-13 15:55 UTC, DmKazakov commented
I have a question about naming convention. For example, how should method corresponding to `FCVT.D.Q` be named? `fcvtdq`? `fcvt_d_q`? Something else?

Also, I need some verification regarding floating point instructions. Some of them have `rm` parameter that defines rounding mode. All I can found in the manual about it:
>All floating-point to integer and integer to floating-point conversion instructions round according
to the rm field.

So it's not clear to me whether `rm` should be a register or an immediate value.

2019-11-13 18:11 UTC, AntonKozlov commented
> I have a question about naming convention. For example, how should method corresponding to `FCVT.D.Q` be named? `fcvtdq`? `fcvt_d_q`? Something else?

I have no strong preference. `fcvtd_dq` is also possible

> Also, I need some verification regarding floating point instructions. Some of them have `rm` parameter that defines rounding mode. All I can find in the manual about it:
> 
> > All floating-point to integer and integer to floating-point conversion instructions round according
> > to the rm field.
> 
> So it's not clear to me whether `rm` should be a register or an immediate value.

A far as I can see `rm` occupies bits 12-14, so it should be 3-bit immediate value

2019-11-21 11:55 UTC, Geckostya approved these changes

2019-11-21 12:15 UTC, merged