Basic version of dispatch_next
azul-research/jdk-riscv pull request #43
Opened 2020-02-18 08:00 UTC by sreznick

2020-02-18 08:09 UTC, DmKazakov commented on src/hotspot/cpu/riscv/interp_masm_riscv_64.cpp
> +  jr(R5_scratch1);
You can't expect R5_scratch1 not to die at this point. I forgot to push commit uniting prolog and epilog so I've created a pr. Check it out.

2020-02-21 09:44 UTC, AntonKozlov requested changes
We also can just remove reference PPC code from our code if we are sure in our understanding and result. I think this is the case.

2020-02-21 09:44 UTC, AntonKozlov commented on src/hotspot/cpu/riscv/interp_masm_riscv_64.cpp
> -  Register bytecode = R6_scratch2;
As far as I understand, we are not sure if we can allocate a temp register, so we do everything in `epilog`.
Then, there is no need to do anything in `prolog`. It's perfectly fine, for example, x86 doesn't do anything here.
I suggest to remove this prolog code completely.

2020-02-23 09:28 UTC, AntonKozlov approved these changes

2020-02-23 19:03 UTC, merged